/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/motherboard.gltf -o src/components/canvas/components/model/MotherBoard.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MotherBoard(props) {
  const { nodes, materials } = useGLTF('/motherboard.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MotherBoard.geometry} material={materials.Material} position={[-0.011, 0, -0.019]} rotation={[Math.PI, 0, Math.PI]} scale={1.662} />
      <mesh geometry={nodes.CPU.geometry} material={nodes.CPU.material} position={[-0.011, -0.012, -0.019]} rotation={[Math.PI, 0, Math.PI]} scale={[0.744, 0.054, 0.744]} />
      <mesh geometry={nodes.LineX.geometry} material={materials['Material.001']} position={[-0.011, 0.087, -0.019]} rotation={[Math.PI, 0, Math.PI]} scale={[0.783, 1, 0.424]} />
      <mesh geometry={nodes.LineY.geometry} material={materials['Material.001']} position={[-0.011, 0.087, -0.019]} rotation={[0, -Math.PI / 2, 0]} scale={[0.783, 1, 0.424]} />
      <mesh geometry={nodes.TextOne.geometry} material={materials['SVGMat.002']} position={[0.365, 0.119, 0.476]} scale={[0.078, 0.067, 0.067]} />
      <mesh geometry={nodes.TextTwo.geometry} material={materials['SVGMat.002']} position={[0.355, 0.114, 0.582]} scale={0.113} />
      <mesh geometry={nodes.path293.geometry} material={materials['Material.001']} position={[0.047, 0.149, 0.085]} rotation={[0, 0, -Math.PI]} scale={[11.976, 6.13, 11.976]} />
      <mesh geometry={nodes.path344.geometry} material={materials['SVGMat.002']} position={[-0.011, 0, -0.019]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.path900.geometry} material={materials['SVGMat.003']} position={[-0.011, 0, -0.019]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.path902.geometry} material={materials['SVGMat.004']} position={[-0.011, 0, -0.019]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.path904.geometry} material={materials['SVGMat.005']} position={[-0.011, 0, -0.019]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.path906.geometry} material={materials['SVGMat.006']} position={[-0.011, 0, -0.019]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.path908.geometry} material={materials['SVGMat.007']} position={[-0.011, 0, -0.019]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/motherboard.gltf')
